minimumReleaseAge: 4320
trustPolicy: no-downgrade
trustPolicyExclude:
  - "detect-port@1.6.1"
  - "semver@6.3.1"
allowBuilds:
  '@swc/core': true
  core-js: true
overrides:
  "serialize-javascript": "^7.0.5"
  "uuid": "^14.0.0"